services:
  kosit-validator:
    image: 'easybill/kosit-validator-xrechnung_3.0.1:v0.0.63'
    ports:
      - '8080:8080'
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 0
      interval: 10s
      retries: 6

  peppol-validator:
    image: 'easybill/peppol-bis-billing-validator:0.2.0'
    ports:
      - '8081:8080'
    healthcheck:
      test: curl --fail http://localhost:8081/health || exit 0
      interval: 10s
      retries: 6