services:
  kosit-validator:
    image: 'easybill/kosit-validator-xrechnung_3.0.2:v0.0.70'
    ports:
      - '8080:8080'
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 0
      interval: 10s
      retries: 6
