version: '3'

tasks:
  start:
    desc: Start the different validators
    cmds:
      - docker compose up --detach --wait --wait-timeout 60

  stop:
    desc: Stop the different validators
    cmds:
      - docker compose down

  tests:
    desc: Runs the PHP tests with the PEST runner
    cmds:
      - ./vendor/bin/pest

  lint:
    desc: Lints the PHP files with PHPStan
    cmds:
      - ./vendor/bin/phpstan analyse

  fixcs:
    desc: Fixes the PHP files with PHP-CS-Fixer
    cmds:
      - ./vendor/bin/php-cs-fixer fix

  generators:
    desc: Runs the code generators (Enums etc.)
    cmds:
      - php ./tools/Generators/CountryCodeEnumGenerator.php
      - php ./tools/Generators/CurrencyCodeEnumGenerator.php
      - php ./tools/Generators/DocumentTypeEnumGenerator.php
      - php ./tools/Generators/ReferenceQualifierEnumGenerator.php
      - php ./tools/Generators/UnitCodeEnumGenerator.php
      - ./vendor/bin/php-cs-fixer fix